public class exception {
    public static void main(String[] args) {
    // try  
    // {  
    // int data=50/0;   
    // }   
    // catch(Exception e)  
    // {  
    //     System.out.println(e);  
    // }  

    // }
    // ----------------------------------------------------------------------------------
    // try{
    //     int d=10/0;
    // }
    // catch(ArithmeticException e){
    //     System.out.println(e);
    // }
    // catch(NullPointerException e){
    //     System.out.println(e);
    // }
//    --------------------------------------------------------------------------------------------
// try{
//         int d=10/0;
//     }
//     catch(ArithmeticException e){
//         System.out.println(e);
//     }
//     catch(ArithmeticException e){
//         System.out.println(e);
//     }    
// NHI CHAL RHA
//-----------------------------------------------------------------------------------------------
// try{
//     System.out.println("1st try");
//     int d=10/0;
// }
// catch(ArithmeticException e){
//     System.out.println(e);
// }
// try{
//     System.out.println("2nd try");
//     int d=10/0;

// }
// finally{
//     System.out.println("Dekhna nhi run karega");
// }
// NI CHAL RHA
//--------------------------------------------------------------------------------------
// try  
//     {  
//     int data=50/0;   
//     }  

//     catch(ArithmeticException e)  
//     {  
//         System.out.println(e);  
//     }  
//     // System.out.println("Hello");
//     finally{
//         System.out.println("Nhi kar rha");
//     }
//------------------------------------------------------------------------------------

    }
}

